language: node_js
node_js:
  - 0.8
before_script:
  - npm install grunt-cli -g
  - grunt build
script: grunt travis --verbose

notifications:
  on_success: change # [always|never|change] default: change
  on_failure: always # [always|never|change] default: always